-- =====================================================
-- FIX DEFINERS AND POPULATE PRODUCTS
-- =====================================================

SET FOREIGN_KEY_CHECKS = 0;

-- 1. Fix broken view definer
DROP VIEW IF EXISTS vw_product_inventory;
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `vw_product_inventory` AS select `p`.`id` AS `id`,`p`.`name` AS `name`,`p`.`sku` AS `sku`,`p`.`stock_quantity` AS `current_quantity`,coalesce(sum(case when `sm`.`movement_type` = 'purchase' or `sm`.`movement_type` = 'return' then `sm`.`quantity_change` else 0 end),0) AS `total_purchased`,coalesce(sum(case when `sm`.`movement_type` = 'sale' then `sm`.`quantity_change` else 0 end),0) AS `total_sold`,`p`.`reorder_level` AS `reorder_level`,`p`.`stock_quantity` <= `p`.`reorder_level` AS `is_low_stock` from (`products` `p` left join `stock_movements` `sm` on(`p`.`id` = `sm`.`product_id`)) group by `p`.`id`,`p`.`name`,`p`.`sku`,`p`.`stock_quantity`,`p`.`reorder_level`;

-- 2. Populate Products
TRUNCATE TABLE products;

INSERT INTO products (name, slug, sku, category_id, category, price, status, short_description, description, meta_title, meta_description, focus_keyword, alt_text, stock_quantity, quantity, main_image_url, is_featured, created_at, updated_at) VALUES
('Solis 5.0kW Off-Grid Single Phase Inverter (Low Voltage)', 'solis-5kw-off-grid-inverter-kenya', 'SOLIS-OG-5KW-LV', 2, 'Inverters', 45000, 'published', 'Complete solar independence for Kenyan homes. 5000W pure sine wave output.', 'Transform your home into an energy-independent powerhouse with the Solis 5.0kW off-grid inverter.', 'Solis 5kW Off-Grid Inverter Kenya | Best Price Nairobi', 'Solis 5.0kW off-grid inverter for Kenyan homes. Pure sine wave, 95% efficiency. Best price Nairobi.', '5kw solar inverter Kenya', 'Solis 5kW off-grid solar inverter', 15, 15, '/products/inverters/solis-5kw-offgrid.jpg', 1, NOW(), NOW()),
('Solis 6.0kW Hybrid Single Phase Inverter (Low Voltage)', 'solis-6kw-hybrid-inverter-kenya', 'SOLIS-HY-6KW-LV', 2, 'Inverters', 135000, 'published', 'Smart energy management with tri-mode operation (Solar/Battery/Grid).', 'High-efficiency hybrid inverter with smart energy management.', 'Solis 6kW Hybrid Inverter Kenya | Smart Solar System', 'Solis 6kW hybrid inverter with tri-mode operation. Reduce bills by 70%. Best price in Nairobi.', '6kw hybrid inverter Kenya', 'Solis 6kW hybrid solar inverter', 10, 10, '/products/inverters/solis-6kw-hybrid.jpg', 1, NOW(), NOW()),
('Solis 8.0kW Hybrid Single Phase Inverter (Low Voltage)', 'solis-8kw-hybrid-inverter-kenya', 'SOLIS-HY-8KW-LV', 2, 'Inverters', 165000, 'published', 'High-power hybrid inverter for large residential systems.', '8kW continuous power output. Ideal for large homes and small businesses.', 'Solis 8kW Hybrid Inverter Kenya | KES 165,000', 'Solis 8kW hybrid inverter for large homes. Dual MPPT technology. Best prices in Nairobi.', '8kw solar inverter Kenya', 'Solis 8kW hybrid solar inverter', 8, 8, '/products/inverters/solis-8kw-hybrid.jpg', 1, NOW(), NOW()),
('Solis 10kW Hybrid Three Phase Inverter (High Voltage)', 'solis-10kw-hybrid-inverter-kenya', 'SOLIS-HY-10KW-3P', 2, 'Inverters', 220000, 'published', 'Three-phase hybrid inverter for commercial and industrial applications.', 'Professional three-phase energy storage solution.', 'Solis 10kW Three Phase Hybrid Inverter Kenya', 'Commercial grade 10kW hybrid inverter. Three-phase support. High voltage battery compatible.', '10kw hybrid inverter Kenya', 'Solis 10kW three phase hybrid inverter', 5, 5, '/products/inverters/solis-10kw-hybrid.jpg', 1, NOW(), NOW()),
('Solis 50kW Grid-Tie Three Phase Inverter', 'solis-50kw-grid-tie-inverter-kenya', 'SOLIS-GT-50KW', 2, 'Inverters', 450000, 'published', 'Industrial grid-tie inverter for large scale solar plants.', 'Maximum efficiency for grid-connected commercial solar projects.', 'Solis 50kW Grid-Tie Inverter Kenya | Industrial Solar', 'Industrial 50kW grid-tie inverter. Tier 1 quality. Best ROI for commercial solar.', '50kw solar inverter Kenya', 'Solis 50kW industrial solar inverter', 3, 3, '/products/inverters/solis-50kw-gt.jpg', 1, NOW(), NOW()),
('Dyness 5.12kWh Lithium Battery A48100', 'dyness-5kwh-lithium-battery-kenya', 'DYNESS-A48100', 1, 'Batteries', 115000, 'published', 'LiFePO4 energy storage with 6000+ cycles. 10-year warranty.', 'The safest and most reliable lithium battery for Kenyan homes.', 'Dyness 5.12kWh Lithium Battery Kenya | Best Price', 'Dyness 5kWh LiFePO4 battery. 6000+ cycles, 10-year warranty. Best price in Nairobi.', '5kwh lithium battery Kenya', 'Dyness 5.12kWh lithium solar battery', 25, 25, '/products/batteries/dyness-5kwh.jpg', 1, NOW(), NOW()),
('Dyness 10.24kWh Lithium Battery Tower', 'dyness-10kwh-lithium-battery-kenya', 'DYNESS-T10', 1, 'Batteries', 225000, 'published', 'High-capacity energy storage for large homes.', '10.24kWh usable energy. Compact tower design.', 'Dyness 10kWh Lithium Battery Kenya | Energy Storage', 'Large capacity 10kWh Dyness battery. Ideal for off-grid living in Kenya.', '10kwh lithium battery Kenya', 'Dyness 10kWh lithium solar battery', 12, 12, '/products/batteries/dyness-10kwh.jpg', 1, NOW(), NOW()),
('X-Batt 5.0kWh Lithium Battery', 'x-batt-5kwh-lithium-battery-kenya', 'XBATT-5KWH', 1, 'Batteries', 95000, 'published', 'Budget-friendly premium lithium storage.', 'High performance LiFePO4 cells at an unbeatable price.', 'X-Batt 5kWh Lithium Battery Kenya | Affordable Solar', 'Affordable 5kWh lithium battery. Reliable backup for Kenyan homes.', 'affordable lithium battery Kenya', 'X-Batt 5kWh lithium battery', 30, 30, '/products/batteries/xbatt-5kwh.jpg', 1, NOW(), NOW()),
('Solar Pro 580W Monocrystalline PERC Panel', 'solar-pro-580w-panel-kenya', 'SP-580W-MONO', 5, 'Solar Panels', 12500, 'published', 'High-efficiency 580W panel with PERC technology.', 'Maximum energy harvest even in low light conditions.', 'Solar Pro 580W Panel Kenya | High Efficiency', '580W Solar Pro panel. 21% efficiency. 25-year warranty. Shop Nairobi.', '580W solar panel Kenya', 'Solar Pro 580W solar panel', 100, 100, '/products/panels/solarpro-580w.jpg', 1, NOW(), NOW()),
('Longi 620W Hi-MO 6 Explorer Panel', 'longi-620w-panel-kenya', 'LONGI-620W', 5, 'Solar Panels', 14500, 'published', 'Tier 1 high-performance panel from Longi Solar.', 'The gold standard in solar efficiency and durability.', 'Longi 620W Solar Panel Kenya | Tier 1 Quality', 'Longi 620W Hi-MO 6 panel. World leading efficiency. Best for large projects.', 'Longi solar panel Kenya', 'Longi 620W solar panel', 150, 150, '/products/panels/longi-620w.jpg', 1, NOW(), NOW()),
('Suntree 32A DC Breaker 2-Pole', 'suntree-32a-dc-breaker-kenya', 'ST-DCB-32A', 3, 'Mounting Accessories', 1800, 'published', 'Essential circuit protection for solar strings.', 'High quality DC breaker rated for 1000V DC.', '32A DC Breaker Kenya | Suntree Solar Protection', 'Suntree 32A DC breaker. Protecting your solar investment. In stock Nairobi.', 'DC breaker Kenya', 'Suntree 32A DC breaker', 200, 200, '/products/accessories/dc-breaker.jpg', 1, NOW(), NOW()),
('MC4 Connector Pair (Male/Female)', 'mc4-connectors-kenya', 'MC4-PAIR', 3, 'Mounting Accessories', 250, 'published', 'Standard IP67 connectors for solar panels.', 'Waterproof and UV resistant solar connectors.', 'MC4 Connectors Kenya | Solar Panel Connectors', 'High quality MC4 connectors. Waterproof IP67. Essential for solar wiring.', 'MC4 connectors Kenya', 'MC4 solar connectors pair', 500, 500, '/products/accessories/mc4.jpg', 1, NOW(), NOW()),
('4mm² DC Solar Cable (Red/Black) - 100m Roll', '4mm-dc-solar-cable-kenya', 'CABLE-4MM-100M', 6, 'DC Solar Cables', 12500, 'published', 'TUV certified PV cable for safe power delivery.', 'Flexible tinned copper conductor with double insulation.', '4mm DC Solar Cable Kenya | 100m Roll', '4mm solar PV cable. TUV certified. 100m rolls available. Shop now.', '4mm solar cable Kenya', '4mm DC solar cable roll', 40, 40, '/products/cables/cable-4mm.jpg', 1, NOW(), NOW()),
('6mm² DC Solar Cable (Red/Black) - 100m Roll', '6mm-dc-solar-cable-kenya', 'CABLE-6MM-100M', 6, 'DC Solar Cables', 16500, 'published', 'High-capacity PV cable for larger arrays.', '6mm core for reduced voltage drop in long runs.', '6mm DC Solar Cable Kenya | Best Price Nairobi', '6mm solar cable for commercial installations. High current capacity.', '6mm solar cable Kenya', '6mm DC solar cable roll', 30, 30, '/products/cables/cable-6mm.jpg', 1, NOW(), NOW()),
('Solar Street Light 200W with Motion Sensor', 'solar-street-light-200w-kenya', 'LIGHT-ST-200W', 4, 'Solar Outdoor Lights', 7500, 'published', 'All-in-one solar light for security and street lighting.', 'Automatic brightness adjustment with motion detection.', '200W Solar Street Light Kenya | Security Lighting', 'Bright 200W solar street light. Motion sensor included. 12+ hours runtime.', 'solar street light Kenya', '200W solar street light', 60, 60, '/products/lights/streetlight-200w.jpg', 1, NOW(), NOW()),
('Solar Garden Flood Light 100W with Remote', 'solar-flood-light-100w-kenya', 'LIGHT-FL-100W', 4, 'Solar Outdoor Lights', 4500, 'published', 'Perfect for garden and compound illumination.', 'Remote controlled with multiple brightness modes.', '100W Solar Flood Light Kenya | Garden Lighting', 'Powerful 100W solar flood light. IP67 waterproof. Remote control.', 'solar flood light Kenya', '100W solar flood light', 85, 85, '/products/lights/floodlight-100w.jpg', 1, NOW(), NOW());

SET FOREIGN_KEY_CHECKS = 1;

-- Show success
SELECT 'Products populated and definers fixed!' as Status;
SELECT COUNT(*) as TotalProducts FROM products;
